services:
  - type: web
    name: email-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: email-assistant-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Email_assistant.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
